// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyRequest.proto

package study.lxy.nettystudy.protobuf.format;

public final class MyRequestProto {
  private MyRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.MyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string function = 1;</code>
     */
    boolean hasFunction();
    /**
     * <code>required string function = 1;</code>
     */
    java.lang.String getFunction();
    /**
     * <code>required string function = 1;</code>
     */
    com.google.protobuf.ByteString
        getFunctionBytes();

    /**
     * <code>required string reqdata = 2;</code>
     */
    boolean hasReqdata();
    /**
     * <code>required string reqdata = 2;</code>
     */
    java.lang.String getReqdata();
    /**
     * <code>required string reqdata = 2;</code>
     */
    com.google.protobuf.ByteString
        getReqdataBytes();
  }
  /**
   * Protobuf type {@code netty.MyRequest}
   */
  public  static final class MyRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.MyRequest)
      MyRequestOrBuilder {
    // Use MyRequest.newBuilder() to construct.
    private MyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyRequest() {
      function_ = "";
      reqdata_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              function_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              reqdata_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return study.lxy.nettystudy.protobuf.format.MyRequestProto.internal_static_netty_MyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return study.lxy.nettystudy.protobuf.format.MyRequestProto.internal_static_netty_MyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest.class, study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest.Builder.class);
    }

    private int bitField0_;
    public static final int FUNCTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object function_;
    /**
     * <code>required string function = 1;</code>
     */
    public boolean hasFunction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string function = 1;</code>
     */
    public java.lang.String getFunction() {
      java.lang.Object ref = function_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          function_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string function = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFunctionBytes() {
      java.lang.Object ref = function_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        function_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQDATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object reqdata_;
    /**
     * <code>required string reqdata = 2;</code>
     */
    public boolean hasReqdata() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string reqdata = 2;</code>
     */
    public java.lang.String getReqdata() {
      java.lang.Object ref = reqdata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqdata_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string reqdata = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReqdataBytes() {
      java.lang.Object ref = reqdata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqdata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFunction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqdata()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, function_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reqdata_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, function_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reqdata_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest)) {
        return super.equals(obj);
      }
      study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest other = (study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest) obj;

      boolean result = true;
      result = result && (hasFunction() == other.hasFunction());
      if (hasFunction()) {
        result = result && getFunction()
            .equals(other.getFunction());
      }
      result = result && (hasReqdata() == other.hasReqdata());
      if (hasReqdata()) {
        result = result && getReqdata()
            .equals(other.getReqdata());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFunction()) {
        hash = (37 * hash) + FUNCTION_FIELD_NUMBER;
        hash = (53 * hash) + getFunction().hashCode();
      }
      if (hasReqdata()) {
        hash = (37 * hash) + REQDATA_FIELD_NUMBER;
        hash = (53 * hash) + getReqdata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.MyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.MyRequest)
        study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return study.lxy.nettystudy.protobuf.format.MyRequestProto.internal_static_netty_MyRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return study.lxy.nettystudy.protobuf.format.MyRequestProto.internal_static_netty_MyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest.class, study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest.Builder.class);
      }

      // Construct using study.lxy.nettystudy.caption8.proto.MyRequestProto.MyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        function_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        reqdata_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return study.lxy.nettystudy.protobuf.format.MyRequestProto.internal_static_netty_MyRequest_descriptor;
      }

      public study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest getDefaultInstanceForType() {
        return study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest.getDefaultInstance();
      }

      public study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest build() {
        study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest buildPartial() {
        study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest result = new study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.function_ = function_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqdata_ = reqdata_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest) {
          return mergeFrom((study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest other) {
        if (other == study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest.getDefaultInstance()) return this;
        if (other.hasFunction()) {
          bitField0_ |= 0x00000001;
          function_ = other.function_;
          onChanged();
        }
        if (other.hasReqdata()) {
          bitField0_ |= 0x00000002;
          reqdata_ = other.reqdata_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFunction()) {
          return false;
        }
        if (!hasReqdata()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object function_ = "";
      /**
       * <code>required string function = 1;</code>
       */
      public boolean hasFunction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string function = 1;</code>
       */
      public java.lang.String getFunction() {
        java.lang.Object ref = function_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            function_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string function = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFunctionBytes() {
        java.lang.Object ref = function_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          function_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string function = 1;</code>
       */
      public Builder setFunction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        function_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string function = 1;</code>
       */
      public Builder clearFunction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        function_ = getDefaultInstance().getFunction();
        onChanged();
        return this;
      }
      /**
       * <code>required string function = 1;</code>
       */
      public Builder setFunctionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        function_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reqdata_ = "";
      /**
       * <code>required string reqdata = 2;</code>
       */
      public boolean hasReqdata() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string reqdata = 2;</code>
       */
      public java.lang.String getReqdata() {
        java.lang.Object ref = reqdata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            reqdata_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string reqdata = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReqdataBytes() {
        java.lang.Object ref = reqdata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqdata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string reqdata = 2;</code>
       */
      public Builder setReqdata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string reqdata = 2;</code>
       */
      public Builder clearReqdata() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqdata_ = getDefaultInstance().getReqdata();
        onChanged();
        return this;
      }
      /**
       * <code>required string reqdata = 2;</code>
       */
      public Builder setReqdataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqdata_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netty.MyRequest)
    }

    // @@protoc_insertion_point(class_scope:netty.MyRequest)
    private static final study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest();
    }

    public static study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MyRequest>
        PARSER = new com.google.protobuf.AbstractParser<MyRequest>() {
      public MyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MyRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyRequest> getParserForType() {
      return PARSER;
    }

    public study.lxy.nettystudy.protobuf.format.MyRequestProto.MyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_MyRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_MyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MyRequest.proto\022\005netty\".\n\tMyRequest\022\020\n" +
      "\010function\030\001 \002(\t\022\017\n\007reqdata\030\002 \002(\tB5\n#stud" +
      "y.lxy.nettystudy.caption8.protoB\016MyReque" +
      "stProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_MyRequest_descriptor,
        new java.lang.String[] { "Function", "Reqdata", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
